name: Pull and Run Docker Image

on:
  push:
    branches:
      - main  # You can specify the branch you want to trigger the workflow on

jobs:
  pull-and-run:
    runs-on: ubuntu-latest
    needs: build-and-push
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Pull Docker Image
        run: docker pull ci-cd:v1

      - name: Run Docker Container
        run: docker run --rm ci-cd:v1
